### ISSUE TITLE
Possible g++ 7.3.1 Internal Compiler error

### ISSUE THREAD

**Issue by nikkej** [avast-tl/yaramod#5]
While compiling [857db32](https://github.com/avast-tl/yaramod/commit/857db32e5a36d083b2df9ce52f1a6eeee5af1167) with g++ 7.3.1, compilation stopped in error:
`yaramod.git/deps/variant/variant.hpp:1900:9: internal compiler error: unexpected expression ‘I’ of kind template_parm_index
         typename T = lib::type_pack_element_t<I, Ts...>,
Please submit a full bug report,`
Trying CLang version 5.0.2, yaramod compiles fine. Full log about these build steps attached. I can report this to gcc upstream but I need some time to isolate specific template pattern to trigger this error.
[g++-7.3.1-internal-compiler-error.log](https://github.com/avast-tl/yaramod/files/2129838/g.-7.3.1-internal-compiler-error.log)

**Comment by metthal** [comment]
I am aware of this issue, however there is not much you can do if your only option is 7.3.1. The bug was already fixed (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84785) and you should be fine if you upgrade to gcc 8.x. If the upgrade is not feasible for you or your Linux distribution, try downgrading to 7.2.x.

**Comment by nikkej** [comment]
Thank you, metthal, confirming this for me. Soon I'll upgrade my distro to Fedora 28 and it brings me gcc 8.x. Meanwhile, I can use LLVM as well.
